name: Publish SDK Package

on:
  push:
    branches: ["main", "master"]
    paths:
      - "packages/sdk/**"
    tags:
      - "v*.*.*"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Needed for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build SDK
        run: bun run sdk:build

      - name: Setup npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish SDK package
        working-directory: ./packages/sdk
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # If this is a tag, publish with the tag version
            bun publish --access public
          else
            # If this is a branch push, publish with the next tag
            bun publish --access public --tag next
          fi
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
